@startuml Context

!include State.puml

abstract class ContextDetector {
  +detect(input: String): Boolean
  +nextToken(): String?
  +transitionTo(state: State): void
  +accept(): void
  +reject(): void
  #initialState(): State
  #endOfInput(): void
  -tokens: List<String>
  -index: Int
  -currentState: State
  -accepted: Boolean
}

@enduml
