@startuml Password
!include Context.puml
!include State.puml

class PasswordContext {

}

class CheckCharacterPasswordState {

}

class ValidPasswordState {

}

class InvalidPasswordState {
}

Context <|-- PasswordContext

State <|-- CheckCharacterPasswordState
State <|-- ValidPasswordState
State <|-- InvalidPasswordState

@enduml
