@startuml EmailAddressStateMachine
title Email Detector State Diagram

state "StartState" as Start
state "Part1State" as Part1
state "NeedPart2State" as NeedPart2
state "Part2State" as Part2
state "NeedPart3State" as NeedPart3
state "Part3State" as Part3
state "Accept" as Accept
state "Reject" as Reject

[*] --> Start

Start --> Part1 : [any except space,@]
Start --> Reject : [space]
Start --> Reject : [@]
Start --> Reject : [end]

Part1 --> Part1 : [any except space,@]
Part1 --> NeedPart2 : [@]
Part1 --> Reject : [space]

NeedPart2 --> Part2 : [any except space,@,.]
NeedPart2 --> Reject : [space]
NeedPart2 --> Reject : [@]
NeedPart2 --> Reject : [.]
NeedPart2 --> Reject : [end]

Part2 --> Part2 : [any except space,@,.]
Part2 --> NeedPart3 : [.]
Part2 --> Reject : [space]
Part2 --> Reject : [@]
Part2 --> Reject : [end]

NeedPart3 --> Part3 : [any except space,@,.]
NeedPart3 --> Reject : [space]
NeedPart3 --> Reject : [@]
NeedPart3 --> Reject : [.]
NeedPart3 --> Reject : [end]

Part3 --> Part3 : [any except space,@,.]
Part3 --> Reject : [space]
Part3 --> Reject : [@]
Part3 --> Reject : [.]
Part3 --> Accept : [end]

Accept --> [*]
Reject --> [*]
@enduml
