class "PasswordDetector.CollectingState" as PasswordCollectingState <<inner>>
class "PasswordDetector.EnforcingState" as PasswordEnforcingState <<inner>>
abstract class "PasswordDetector.PasswordState" as PasswordStateBase <<inner>>
interface "PasswordDetector.ComplexityState" as PasswordComplexityState <<inner>>
abstract class "PasswordDetector.RejectingComplexityState" as PasswordRejectingComplexityState <<inner>>
class "PasswordDetector.MissingUpperAndSpecial" as PasswordMissingUpperAndSpecial <<inner>>
class "PasswordDetector.MissingUpperWithTrailingSpecial" as PasswordMissingUpperWithTrailingSpecial <<inner>>
class "PasswordDetector.MissingUpperNoTrailingSpecial" as PasswordMissingUpperNoTrailingSpecial <<inner>>
class "PasswordDetector.MissingSpecial" as PasswordMissingSpecial <<inner>>
class "PasswordDetector.UpperAndSpecialTrailing" as PasswordUpperAndSpecialTrailing <<inner>>
class "PasswordDetector.UpperAndSpecialReady" as PasswordUpperAndSpecialReady <<inner>>
State <|.. PasswordStateBase
PasswordStateBase <|-- PasswordCollectingState
PasswordStateBase <|-- PasswordEnforcingState
PasswordComplexityState <|.. PasswordRejectingComplexityState
PasswordComplexityState <|.. PasswordUpperAndSpecialReady
PasswordRejectingComplexityState <|-- PasswordMissingUpperAndSpecial
PasswordRejectingComplexityState <|-- PasswordMissingUpperWithTrailingSpecial
PasswordRejectingComplexityState <|-- PasswordMissingUpperNoTrailingSpecial
PasswordRejectingComplexityState <|-- PasswordMissingSpecial
PasswordRejectingComplexityState <|-- PasswordUpperAndSpecialTrailing
PasswordDetector *-- PasswordCollectingState
PasswordDetector *-- PasswordEnforcingState
PasswordDetector *-- PasswordStateBase
PasswordDetector *-- PasswordComplexityState
PasswordDetector *-- PasswordRejectingComplexityState
PasswordDetector *-- PasswordMissingUpperAndSpecial
PasswordDetector *-- PasswordMissingUpperWithTrailingSpecial
PasswordDetector *-- PasswordMissingUpperNoTrailingSpecial
PasswordDetector *-- PasswordMissingSpecial
PasswordDetector *-- PasswordUpperAndSpecialTrailing
PasswordDetector *-- PasswordUpperAndSpecialReady
